### ISSUE TITLE
[Bug] UI bugs

### ISSUE THREAD

**Issue by shivanshvermak** [toasterofbread/spmp#119] opened 2023-08-20 09:22 UTC
Talking about these bugs (the space left in bottom in the first screenshot and top in the second one):
![Screenshot_20230820-144858](https://github.com/toasterofbread/spmp/assets/15206857/ee3bafb8-53a9-4027-b0e7-82c311270fbe)
![Screenshot_20230820-144826](https://github.com/toasterofbread/spmp/assets/15206857/69793d0a-8883-44ff-8c5b-73882e0ab4d3)

Not logged in
hentaiOS, a13
1.4.0 version

---
Other than these, I saw the following problem:
Just normally downloaded the release 1.4.0 (tried both FDroid and GitHub releases) and opened the app and I see just "YouTube feed parsing failed". I couldn't screenshot it because I refresh it 2-3 times and it fixed itself. But I did upload logs: https://paste.ee/p/5SrMY

**Comment by toasterofbread** [comment] 2023-08-20 18:26
Thanks for the report. This issue has been known for a while but has been really hard to fix because of the amount of combinations of navbar types and OS versions to test. I will probably get around to fixing it properly soon.

The second issue is a duplicate of #117, which has been fixed on main.

**Comment by toasterofbread** [comment] 2023-08-25 19:06
[0c4b35d](https://github.com/toasterofbread/spmp/commit/0c4b35d41ad739e7e9d5d6afeb35eeda0bdcda1f) should have fixed or at least improved this issue. It would be great if you could [test](https://github.com/toasterofbread/spmp/actions/runs/5979523063) it and report any differences.

**Comment by shivanshvermak** [comment] 2023-08-25 19:31
![Screenshot_20230826-005808](https://github.com/toasterofbread/spmp/assets/15206857/f02a7be8-5333-4e27-90e0-750b2cb6e3d5)
![Screenshot_20230826-005750](https://github.com/toasterofbread/spmp/assets/15206857/dbbcbb51-4945-49d4-a8f3-410d84f544cb)
Thanks! Checked, one issue is fixed and one isn't. The music player goes above the status bar

**Comment by toasterofbread** [comment] 2023-08-25 19:48
With the newest build you just tested, please go to the app settings (tap the note icon on the top-right, then the settings icon), go to the development section at the bottom, tap on "UI debug info", and screenshot that page.

**Comment by shivanshvermak** [comment] 2023-08-25 19:51
Here
![Screenshot_20230826-012025](https://github.com/toasterofbread/spmp/assets/15206857/3868352c-90ae-450b-8bad-22649b69ae28)

**Comment by toasterofbread** [comment] 2023-08-26 00:07
Should be fixed by [03cf7bb](https://github.com/toasterofbread/spmp/commit/03cf7bb6841dcfb66a829e755b899aadd57cc5b4), test build is [here](https://github.com/toasterofbread/spmp/actions/runs/5981500078).

**Comment by shivanshvermak** [comment] 2023-08-26 00:31
Now appears perfectly! Thanks!

**Closed** 2023-08-26 08:12 UTC
Labels: Bug
