### ISSUE TITLE
Nothing works anymore.

### ISSUE THREAD

**Issue by Exw27** [toasterofbread/spmp#107] opened 2023-08-11 23:37 UTC
It used to work now no songs play's at all it just infinitely loads, Downloading does not work to.

nown Source:2)
	at com.toasterofbread.spmp.PlayerDownloadService.startDownload$lambda-6(Unknown Source:21)
	at com.toasterofbread.spmp.PlayerDownloadService.$r8$lambda$canIeEMyQgjDxuesY6191-sqmSI(Unknown Source:0)
	at com.toasterofbread.spmp.PlayerDownloadService$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by surajak** [comment] 2023-08-13 01:09
Randomly only one song or of 10 plays. Others don't. I tried repeatedly closing opening, clearing recents.

**Comment by toasterofbread** [comment] 2023-08-13 09:30
Please include the entire error message and stacktrace. What versions of SpMp and Android are you using?

**Comment by Exw27** [comment] 2023-08-13 13:09
> Please include the entire error message and stacktrace. What versions of SpMp and Android are you using?

That was the entire error message when i was trying to download.

I am using Android 13, with the latest SpMp.

**Comment by toasterofbread** [comment] 2023-08-13 22:45
It's definitely been cut off somehow, without the full message it'll be pretty hard to find the cause.

What makes the message appear? Where does it show up? Does it appear every time?

**Comment by Exw27** [comment] 2023-08-13 23:05
> It's definitely been cut off at the start somehow, without the full message it'll be pretty hard to find the cause.
> 
> What makes the message appear? Where does it show up? Does it appear every time?

The error message appears occasionally when trying to download a song. But as the other person wrote, nothing plays, only 1 in 20 songs manages to play.

**Comment by toasterofbread** [comment] 2023-08-16 01:32
I started experiencing a similar issue recently where songs would take quite a while to load, usually about 20 seconds, but they would always load eventually. 

The issue was resolved for me by updating the NewPipeExtractor library (which handles song loading) within the code. You can [test to see if this fixes it for you](https://github.com/toasterofbread/spmp/actions/runs/5861231960), but if it doesn't then I don't really know how I'd troubleshoot this issue.

**Comment by toasterofbread** [comment] 2023-08-17 13:21
I've made a [minor release](https://github.com/toasterofbread/spmp/releases/tag/v0.1.4) which just adds this fix on top of the previous release.

**Closed by toasterofbread** 2023-08-17 13:21 UTC
Labels: Bug
