### ISSUE TITLE
[Android] App crashes when playing music from the library screen

### ISSUE THREAD

**Issue by Mibanfi** [toasterofbread/spmp#344] opened 2024-07-18 15:48 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [x] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open app
2. Click on the note icon on the top right
3. Click on any music from the sub-menus that appear

### Expected behavior

Music is played normally

### Actual behavior

Error message appears and app is unresponsive until closed and opened again

### Logs

https://paste.ee/p/DMDh5

### SpMp version

0.3.2

### SpMp platform

Android

### OS version

Android 12

**Comment by toasterofbread** [comment] 2024-07-18 16:40
This appears to be a duplicate of #290 which should have been fixed by c087cf57d445dffb642b351c9733583a743a3cc3. Please confirm the latest commit you're able to reproduce this bug with.

**Comment by Mibanfi** [comment] 2024-07-18 18:08
I can confirm the bug happens on both the latest GitHub release and the recommended F-Droid release.
Should I try building from source as well?

**Comment by toasterofbread** [comment] 2024-07-18 18:12
You checked the 'I am able to reproduce the bug with the latest debug version' box in your issue. I'm just wondering what the commit ID of the version you used was.

**Comment by Radoom** [comment] 2024-08-04 22:11
Same crashing for me in v 0.3.2,
but works in Version 0.4.0 Release Candidate 1

**Closed** 2024-08-04 22:13 UTC
Labels: Bug
