### ISSUE TITLE
No Last.Fm scrobbler on spmp pc desktop 

### ISSUE THREAD

**Issue by Azzman1984** [toasterofbread/spmp#361] opened 2024-08-23 21:58 UTC
There's no Last.fm built in scrobbler on the pc desktop version of the app as far as I know so if their an chance to be added on an update then I would be greatful.

**Comment by toasterofbread** [comment] 2024-08-23 22:03
Duplicate of #102

**Closed by toasterofbread** 2024-08-23 22:03 UTC
