### ISSUE TITLE
Problem with downloaded songs

### ISSUE THREAD

**Issue by enderplay9** [toasterofbread/spmp#346] opened 2024-07-27 21:50 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

First I enter the application everything is normal I enter the downloaded songs folder in the application then I get a bug and the application freezes

### Expected behavior

What I should do is play the song 

### Actual behavior

A screen appears telling me a text 

### Logs

https://paste.ee/p/dKTyt

### SpMp version

0.3.2

### SpMp platform

Android

### OS version

Android 13

**Comment by toasterofbread** [comment] 2024-07-27 23:28
Duplicate of #290

**Closed by toasterofbread** 2024-07-27 23:28 UTC
Labels: Bug
