### ISSUE TITLE
KuGou lyrics provider not working

### ISSUE THREAD

**Issue by ElizabethWega** [toasterofbread/spmp#104] opened 2023-08-02 15:15 UTC
Android version: 13
App version: 0.1.3
Issue description: When I set **KuGou** as a default lyrics provider and press an assigned button to fetch the lyrics, all I get is a _Loading lyrics_ text accompanied with a loading bar, which means no lyrics actually appearing on the screen. Once I change the default provider to **PetitLyrics** and use the assigned buttons to look up the lyrics in English via **KuGou** (I tried using PetitLyrics and it just doesn't work for me since I keep getting irrelevant results), I'm met with the following error: _java.lang.RuntimeException: Lyrics not loaded._ I am certain that the lyrics do exist on **KuGou**, for I requested the lyrics (for the same song; Fluorescent by MDSN) in two different apps using **KuGou** provider (_SpMp_ and _ViMusic_). 
I have no clue if this is an app's or provider's fault but whatever the case any troubleshooting is greatly appreciated. Thanks in advance!

**Comment by toasterofbread** [comment] 2023-08-13 09:28
Yeah, I've noticed this issue as well. Will fix soon.

**Comment by toasterofbread** [comment] 2023-08-14 14:29
Strange, it seems some lyrics on Kugou (including for the song you mentioned) can't be downloaded with the method I'm using. Lyrics do appear in the search results, but trying to download the lyrics using the ID that Kugou provides leads to an empty response.

I'm using ViMusic as the reference for implementing Kugou but it doesn't seem to include a working method.  I tried loading the lyrics for the same song using ViMusic and it didn't work there either. Can you confirm that ViMusic is still able to load lyrics for Fluorescent by MDSN?

**Comment by ElizabethWega** [comment] 2023-08-15 11:21
> Strange, it seems some lyrics on Kugou (including for the song you mentioned) can't be downloaded with the method I'm using. Lyrics do appear in the search results, but trying to download the lyrics using the ID that Kugou provides leads to an empty response.
> 
> I'm using ViMusic as the reference for implementing Kugou but it doesn't seem to include a working method. I tried loading the lyrics for the same song using ViMusic and it didn't work there either. Can you confirm that ViMusic is still able to load lyrics for Fluorescent by MDSN?

Yes, it shows unsynchronized lyrics. Maybe that's the issue? Synchronized/unsynchronized lyrics?

**Comment by toasterofbread** [comment] 2023-08-15 17:40
I'm using the latest ViMusic and it doesn't load either type. Is this the exact song you're using?
https://music.youtube.com/watch?v=BOgqXFWqKb8
<img src="https://github.com/toasterofbread/spmp/assets/44363049/2a19a752-bfa2-4c2e-befb-78f858c98506" height = 600/>

**Comment by ElizabethWega** [comment] 2023-08-15 18:29
> I'm using the latest ViMusic and it doesn't load either type. Is this the exact song you're using? https://music.youtube.com/watch?v=BOgqXFWqKb8 <img alt="" height="600/" src="https://user-images.githubusercontent.com/44363049/260791182-2a19a752-bfa2-4c2e-befb-78f858c98506.png">

This one: https://music.youtube.com/watch?v=Zo5pu7w1cg8

**Comment by toasterofbread** [comment] 2023-08-15 19:15
Thanks. I've figured out what the issue is now, ViMusic only uses Kugou for synchronized lyrics. It uses YouTube Music for unsynchronised music (and I think YouTube uses MusixMatch). I'll implement a way to view the lyrics from YouTube in SpMp as well.

**Comment by ElizabethWega** [comment] 2023-08-15 19:49
> Thanks. I've figured out what the issue is now, ViMusic only uses Kugou for synchronized lyrics. It uses YouTube Music for unsynchronised lyrics (and I think YouTube Music uses MusixMatch). I'll implement a way to view the lyrics from YouTube in SpMp as well.

Oh wow! I did not know that! Thank you! Looking forward to the new update 🙂

**Comment by toasterofbread** [comment] 2023-08-15 23:23
Added YouTube Music as a lyrics source. Will be in the next update :+1:

**Closed** 2023-08-15 23:23 UTC
Labels: Bug
