### ISSUE TITLE
Fail play from local custom download dir

### ISSUE THREAD

**Issue by eennbb** [toasterofbread/spmp#349] opened 2024-08-05 02:59 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Play song from local

### Expected behavior

Play song

### Actual behavior

Error

### Logs

https://paste.ee/p/WiNbN

### SpMp version

v0.3.2 

### SpMp platform

Android

### OS version

Android  14

**Comment by toasterofbread** [comment] 2024-08-05 07:48
Duplicate of #290

**Closed** 2024-08-05 07:48 UTC
Labels: Bug
