### ISSUE TITLE
[Bug] Player UI not showing correctly

### ISSUE THREAD

**Issue by DuncanTDP** [toasterofbread/spmp#135] opened 2023-09-05 02:03 UTC
**Describe the bug**

On my phone (a Google pixel 7) the full screen music player is not actually using the full screen. Instead, the top portion of the screen shows the bottom of the home UI. I really really love your app, but this really bothers me more than you could know. I tried the most recent release and the last. Both logged in and unlocked on.

**Environment**
- OS name and version Android 13
- SpMp version 0.1.4

**Screenshots**
![Screenshot_20230904-215730](https://github.com/toasterofbread/spmp/assets/91847139/6402ae52-187a-4868-b4eb-e6dd5eeef578)

**Comment by toasterofbread** [comment] 2023-09-05 07:50
Is the issue still present in the [latest build](https://github.com/toasterofbread/spmp/actions/runs/6078528287)? If not, this is a duplicate of #119.

**Comment by DuncanTDP** [comment] 2023-09-06 01:25
Oh, yes it is a duplicate I'm sorry. I didn't realize their was a later
release than in the releases section. Thank you for the response. Have a
good day.

**Closed** 2023-09-06 11:26 UTC
Labels: Bug
