### ISSUE TITLE
Playlist Play button throwes a error 

### ISSUE THREAD

**Issue by ADIT011007** [toasterofbread/spmp#182] opened 2023-10-27 09:28 UTC
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1 : play a song and click on the three dots on top right 
2 : create a playlist without changing the name .
3 : add the song to that playlist
4 : open the playlist menu then click on the playlist u just created 
5 : change the name of playlist
6 : then click on the playlist Play button 

### Expected behavior

It should play the music from the playlist 

### Actual behavior

First it shows a big error then starts playing that song . And if u try going back to the app then it glitches 

### Screenshots / recordings

![Screenshot_2023-10-27-14-57-00-024_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/77261726/067d957d-9586-4d2e-9df5-a7f4c0ccf4b0)

### Logs

https://paste.ee/p/J2zYv

### SpMp version

0.2.3

### Android version

Android 11

**Comment by toasterofbread** [comment] 2023-10-27 17:41
Which commit were you able to reproduce this with? This should have been fixed by b66d9c092dfdf01dcd1d37679d6c3b0982c5e2e2.

**Comment by ADIT011007** [comment] 2023-10-27 18:15
> Which commit were you able to reproduce this with? This should have been fixed by [b66d9c0](https://github.com/toasterofbread/spmp/commit/b66d9c092dfdf01dcd1d37679d6c3b0982c5e2e2).
How can I find that ?

**Comment by ADIT011007** [comment] 2023-10-27 18:17
> You marked the "I am able to reproduce the bug with the latest debug version" box. Which debug version were you using?

I installed your app from fdroid .

**Comment by toasterofbread** [comment] 2023-10-27 18:19
So you haven't reproduced this with the latest debug version? If so, then this is a duplicate of #178.

**Comment by ADIT011007** [comment] 2023-10-27 18:21
> So you haven't reproduced this with the latest debug version? If so, then this is a duplicate of #178.

Oh i see.  My bad sorry . I will close the issue 😔

**Closed** 2023-10-27 18:21 UTC
Labels: Bug
