### ISSUE TITLE
Not playing next song in my play list

### ISSUE THREAD

**Issue by ShadowWalkerM** [toasterofbread/spmp#296] opened 2024-04-26 12:03 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Make a play list
Play first song 
And 2nd song is recommendation song not the second song in play list

### Expected behavior

Completely play the play list

### Actual behavior

Play normally first song and then start recommendation  songs not next song in play list

### Screenshots / recordings

![Screenshot_20240426-171911](https://github.com/toasterofbread/spmp/assets/151029272/f3a79f8c-044e-4d78-a8b8-c130f0539393)
![Screenshot_20240426-171915](https://github.com/toasterofbread/spmp/assets/151029272/451c51e0-64f3-44b7-b6b9-000c7804062e)

### Logs

java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class java.util.Collections$SingletonMap (Kotlin reflection is not available), with Content-Type: null.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(SourceFile:256)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:4)
	at io.ktor.client.engine.HttpClientEngine$install$1.invoke(SourceFile:5)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SourceFile:8)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(SourceFile:161)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(SourceFile:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.client.HttpClient$4.invokeSuspend(SourceFile:197)
	at io.ktor.client.HttpClient$4.invoke(SourceFile:42)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SourceFile:36)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SourceFile:28)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SourceFile:24)
	at io.ktor.util.pipeline.Pipeline.execute(SourceFile:190)
	at io.ktor.client.HttpClient.execute$ktor_client_core(SourceFile:64)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(Unknown Source:64)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:1)
	at io.ktor.client.statement.HttpStatement.execute(SourceFile:2)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe(SourceFile:341)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt.uploadErrorToPasteEe$default(Unknown Source:19)
	at com.toasterofbread.spmp.ui.component.ErrorInfoDisplayKt$ExpandedContent$2$1$1$1$2$1.invokeSuspend(SourceFile:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(SourceFile:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

### SpMp version

0.3.1

### SpMp platform

Android

### OS version

Android 11

### Additional information

This did not happen in older versions

**Comment by ShadowWalkerM** [comment] 2024-04-26 12:29
Old version works fine(version 0.3.0)
![Screenshot_20240426-175532](https://github.com/toasterofbread/spmp/assets/151029272/e8c60d2b-adbd-49c0-a255-6cee90720f92)
![Screenshot_20240426-175536](https://github.com/toasterofbread/spmp/assets/151029272/1d9ece0f-6c11-4b18-b227-bd8b56cb6067)

**Comment by ShadowWalkerM** [comment] 2024-04-27 06:59
> Where/when were those logs produced? Please send the equivalent logs taken on the latest debug build instead.

Um so recommendation songs there cuz i have internet connection so i downloaded first 2 songs and turned off int connection and tried to play those 2 songs when i pressed first song and went to song queue and there was first song and error msg and that msg is in log section of issue report 
![Screenshot_20240427-121620](https://github.com/toasterofbread/spmp/assets/151029272/8d6b1d93-acf0-470f-b5ec-acb381bb0d97)
![Screenshot_20240427-121630](https://github.com/toasterofbread/spmp/assets/151029272/2f65a872-fc36-4636-9de8-b8f37f43e8e8)
![Screenshot_20240427-121632](https://github.com/toasterofbread/spmp/assets/151029272/749f5c14-a62b-4814-9c70-9c3f4349bb76)

**Comment by ShadowWalkerM** [comment] 2024-04-27 07:16
> Where/when were those logs produced? Please send the equivalent logs taken on the latest debug build instead
Um so recommendation songs there cuz i have internet connection so i downloaded first 2 songs and turned off int connection and tried to play those 2 songs when i pressed first song and went to song queue and there was first song and error msg and that msg is in log section of issue report 
And how do i send latest debug build log idk how there no error msg other than that

![Screenshot_20240427-121620](https://github.com/toasterofbread/spmp/assets/151029272/a69f350f-433e-4e4c-95da-4226b811caac)
![Screenshot_20240427-121630](https://github.com/toasterofbread/spmp/assets/151029272/bc024e41-eacc-46b7-bf26-025b9d1dd560)
![Screenshot_20240427-121632](https://github.com/toasterofbread/spmp/assets/151029272/9fb84612-58d4-4b2f-84da-d9cd64b0fb07)

**Comment by toasterofbread** [comment] 2024-04-28 09:27
Which commit are you testing this on? I'm not able to reproduce this.

**Comment by ShadowWalkerM** [comment] 2024-04-29 04:33
> Which commit are you testing this on? I'm not able to reproduce this.

Commit mean? if its version its 0.3.1 app version in android 11

**Comment by toasterofbread** [comment] 2024-04-29 09:22
You ticked the box saying `I am able to reproduce the bug with the latest debug version`. Which debug apk did you use?

**Comment by ShadowWalkerM** [comment] 2024-04-29 11:41
> You ticked the box saying `I am able to reproduce the bug with the latest debug version`. Which debug apk did you use?

android-armeabi-7a.apk(0.3.1) is the apk i used and 0.3.2 version have same problem

**Comment by toasterofbread** [comment] 2024-04-29 15:41
v0.3.2 is not the latest build. Please don't tick the `I am able to reproduce the bug with the latest debug version` box without testing the latest debug version (which is linked to in the issue template). 

I'm fairly sure this bug is already fixed on main, but if not then please provide a stack trace from the latest debug build.

**Closed by toasterofbread** 2024-04-29 15:41 UTC
Labels: Bug
