### ISSUE TITLE
Can't play music when connected to wifi

### ISSUE THREAD

**Issue by adarshmk354** [toasterofbread/spmp#428] opened 2024-12-27 15:04 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

When we play music in wifi

### Expected behavior

Should play the music without any trouble 

### Actual behavior

It's not playing anything 

### Logs

java.lang.RuntimeException: No valid formats returned by getVideoFormats(Z-6-EozmF6Q)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt.getSongFormats(Unknown Source:141)
	at com.toasterofbread.spmp.model.mediaitem.song.SongAudioQualityKt$getSongFormats$1.invokeSuspend(Unknown Source:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:112)
	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:98)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:95)

### SpMp version

0.4.2

### SpMp platform

Android

### OS version

Android 15

**Comment by toasterofbread** [comment] 2024-12-27 18:11
Duplicate of #416

**Closed by toasterofbread** 2024-12-27 18:11 UTC
Labels: Bug
