### ISSUE TITLE
[Bug] Player not filling full height of screen

### ISSUE THREAD

**Issue by MrConqueror** [toasterofbread/spmp#79] opened 2023-07-19 06:41 UTC
is there a setting where to make the player look like this?
![Screenshot_2023-07-19-14-38-44-642_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/102837820/105f5d3a-9f18-491d-b5d8-de255583caa0)

i prefer the player above to this one below.
![Screenshot_2023-07-19-14-38-50-051_com toasterofbread spmp](https://github.com/toasterofbread/spmp/assets/102837820/451c530a-5474-40a8-be64-7d72578119f3)

**Comment by toasterofbread** [comment] 2023-07-19 07:47
Weird, it's supposed to look like that (it does on my device). 
What version of Android are you using? And are you using any mods like Magisk or Xposed modules which might modify the status bar or navigation bar height?

**Comment by danielphan2003** [comment] 2023-07-19 12:48
There is also the case when the player disappear after a while but the FAB is still behind the status bar: ![Screenshot_20230719-194612.png](https://github.com/toasterofbread/spmp/assets/34669737/384c9852-13de-4d80-acf4-0ff3e62f003b)

**Comment by toasterofbread** [comment] 2023-07-19 15:34
What version of Android are you experiencing this on?

**Comment by danielphan2003** [comment] 2023-07-19 19:04
> What version of Android are you experiencing this on?

It's Android 13 (Pixys OS)

**Comment by toasterofbread** [comment] 2023-07-19 21:31
I've found the cause of the bug. I was testing the app with my navigation bar hidden, so I never made the UI take the navbar height into account. I'll get a fix out soon.

**Comment by toasterofbread** [comment] 2023-07-21 00:28
Should be fixed now. I've tested fairly thoroughly with each navbar type, but let me know if anything still looks weird.

**Closed** 2023-07-25 22:16 UTC
Labels: Bug
