### ISSUE TITLE
breaks when you tab out

### ISSUE THREAD

**Issue by 32bitx64bit** [toasterofbread/spmp#168] opened 2023-10-15 01:36 UTC
### Checklist

- [] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Open app
Tab out
Tab back in

### Expected behavior

Tab out
Tab in with app working properly

### Actual behavior

Tab out
Tab in and the app just freezes 

### Screenshots / recordings

https://gofile.io/d/LRQK5X

### Logs

Doesn't produce log

### SpMp version

0.2.3

### Android version

android 12 

### Additional information

Using Graphenos for privacy.

**Comment by 32bitx64bit** [comment] 2023-10-15 01:39
Issue DOESNT exist in 0.2.2. Whatever happened in 0.2.3 broke something.

**Comment by toasterofbread** [comment] 2023-10-15 22:53
Please find and upload the logs associated with the crash using Logcat, a similar tool, or by [capturing a bug report](https://developer.android.com/studio/debug/bug-report).

**Comment by 32bitx64bit** [comment] 2023-10-19 00:51
> Please provide the logs associated with the crash using Logcat, a similar tool, or by [capturing a bug report](https://developer.android.com/studio/debug/bug-report).

Zero idea how to do any of that,y experience with android bug crap is very little.

**Comment by 32bitx64bit** [comment] 2023-10-19 22:38
> > Please provide the logs associated with the crash using Logcat, a similar tool, or by [capturing a bug report](https://developer.android.com/studio/debug/bug-report).
> 
> Zero idea how to do any of that, experience with android bug crap is very little.

I doubt its a issue on graphenOS. As the last version worked perfectly fine, you could probably recreate it on your device. As I have a hunch that everyone is experiencing this

**Comment by toasterofbread** [comment] 2023-10-19 22:42
If I was able to reproduce this I would've fixed it long ago. There's basically nothing I can do without the crash logs unfortunately.

There are plenty of apps on the Play Store that let you view app logs, like [this one](https://play.google.com/store/apps/details?id=com.conena.logcat.reader).

**Comment by 32bitx64bit** [comment] 2023-10-20 18:04
> If I was able to reproduce this I would've fixed it long ago. There's basically nothing I can do without the crash logs unfortunately.
> 
> There are plenty of apps on the Play Store that let you view app logs, like [this one](https://play.google.com/store/apps/details?id=com.conena.logcat.reader).

Ok I'll give this a try. If able to produce a log I'll drop it here in a minute

**Comment by 32bitx64bit** [comment] 2023-10-20 18:17
2023-10-19 17:36:58.304 17365 17365 com.toasterofbread.spmp E AndroidRuntime : FATAL EXCEPTION: main
Process: com.toasterofbread.spmp, PID: 17365
android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class androidx.compose.foundation.lazy.layout.DefaultLazyKey
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:5035)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4881)
	at android.os.Parcel.readValue(Parcel.java:4641)
	at android.os.Parcel.readValue(Parcel.java:4410)
	at android.os.Parcel.readMapInternal(Parcel.java:5327)
	at android.os.Parcel.readHashMapInternal(Parcel.java:5312)
	at android.os.Parcel.readValue(Parcel.java:4637)
	at android.os.Parcel.readValue(Parcel.java:4410)
	at android.os.Parcel.readListInternal(Parcel.java:5419)
	at android.os.Parcel.readArrayListInternal(Parcel.java:5438)
	at android.os.Parcel.readValue(Parcel.java:4671)
	at android.os.Parcel.readValue(Parcel.java:4410)
	at android.os.Parcel.readMapInternal(Parcel.java:5328)
	at android.os.Parcel.readHashMapInternal(Parcel.java:5312)
	at android.os.Parcel.readValue(Parcel.java:4637)
	at android.os.Parcel.readValue(Parcel.java:4410)
	at android.os.Parcel.readListInternal(Parcel.java:5419)
	at android.os.Parcel.readArrayListInternal(Parcel.java:5438)
	at android.os.Parcel.readValue(Parcel.java:4671)
	at android.os.Parcel.readValue(Parcel.java:4410)
	at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4508)
	at android.os.Parcel$LazyValue.apply(Parcel.java:4467)
	at android.os.BaseBundle.unwrapLazyValueFromMapLocked(BaseBundle.java:417)
	at android.os.BaseBundle.getValueAt(BaseBundle.java:403)
	at android.os.BaseBundle.getValue(BaseBundle.java:383)
	at android.os.BaseBundle.getValue(BaseBundle.java:366)
	at android.os.BaseBundle.getValue(BaseBundle.java:359)
	at android.os.Bundle.getParcelableArrayList(Bundle.java:1046)
	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(SourceFile:247)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:16)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:2)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
	at coil.util.-Logs.CompositionLocalProvider(SourceFile:182)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(SourceFile:1)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:7)
	at _COROUTINE._BOUNDARY.invokeComposable(SourceFile:1)
	at androidx.compose.runtime.ComposerImpl.doCompose(SourceFile:131)
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(SourceFile:1)
	at androidx.compose.runtime.CompositionImpl.composeContent(SourceFile:18)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(SourceFile:30)
	at androidx.compose.runtime.CompositionImpl.setContent(Unknown Source:10)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(SourceFile:11)
	at androidx.compose.ui.platform.WrappedComposition.setContent(SourceFile:23)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Unknown Source:18)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(SourceFile:23)
	at androidx.lifecycle.LifecycleRegistry.addObserver(SourceFile:107)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(SourceFile:11)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:115)
	at android.view.View.dispatchAttachedToWindow(View.java:21980)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)

This is what I saw.

**Comment by 32bitx64bit** [comment] 2023-10-20 18:19
Also this was another error

2023-10-19 17:36:58.305 17365 17365 com.toasterofbread.spmp E AndroidRuntime : at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3014)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.lang.NoSuchFieldException: CREATOR
	at java.lang.Class.getField(Class.java:2337)
	at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:5012)
	... 73 more

**Comment by 32bitx64bit** [comment] 2023-10-20 18:30
Thw app seem to have reported a error too when I opened it
https://paste.ee/p/tBrwI

**Comment by toasterofbread** [comment] 2023-10-24 18:41
Looks like it might have something to do with proguard. Have you tried with a debug APK?

**Comment by 32bitx64bit** [comment] 2023-10-25 03:02
> Looks like it might have something to do with proguard. Have you tried with a debug APK?

Yes, the debug build "works" its very laggy

**Comment by toasterofbread** [comment] 2023-10-26 14:58
Please try d5d16c7475b3f0e43d75368501bda209f969a476

**Comment by 32bitx64bit** [comment] 2023-10-26 17:22
> Please try [d5d16c7](https://github.com/toasterofbread/spmp/commit/d5d16c7475b3f0e43d75368501bda209f969a476)

Fixed thw tab out use it seems, but it doesn't seem the youtube page loads 
https://paste.ee/p/TULXv

**Comment by toasterofbread** [comment] 2023-10-26 17:26
> Fixed thw tab out use it seems, but it doesn't seem the youtube page loads

Whoops, forgot to remove some test code. Will be fixed in the next commit.

**Closed by toasterofbread** 2023-10-26 17:26 UTC
Labels: Bug
