### ISSUE TITLE
java.lang.IllegalStateException: Check failed.
	at com.toasterofbread.composekit.platform.PlatformFile.moveTo(Unknown Source:30)
	at com.toasterofbread.spmp.platform.download.SongDownloader$performDownload$2.invokeSuspend(SourceFile:415)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)


### ISSUE THREAD

**Issue by ASHOK9585** [toasterofbread/spmp#260] opened 2024-03-20 07:41 UTC

**Comment by ASHOK9585** [comment] 2024-03-20 07:42
Download the song and this error  message on screen

**Comment by toasterofbread** [comment] 2024-03-20 12:23
Please use the issue template when reporting bugs. This is also a duplicate of #247. Additionally, the information provided in this error message was improved in ca9d06a84abf4c79674feabfa3051a3521f432d5, please provide a stack trace produced by that commit or later (in #247).

**Closed by toasterofbread** 2024-03-20 12:23 UTC
