### ISSUE TITLE
MUSIC_PAGE_TYPE_UNKNOWN when loading some playlists

### ISSUE THREAD

**Issue by BlacRyu** [toasterofbread/spmp#211] opened 2023-12-09 05:48 UTC
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Log in to YouTube
2. Go to playlists screen.
3. Tap on certain Account playlists.

### Expected behavior

Playlist should open and show a list of songs.

### Actual behavior

A crash screen shows up with the error MUSIC_PAGE_TYPE_UNKNOWN

### Screenshots / recordings

<details>
  <summary>Screenshot of where the app is frozen after the error.</summary>

  ![image](https://github.com/toasterofbread/spmp/assets/10762433/f5a6871e-9b39-4135-8013-e9ead80513bb)

</details>

### Logs

paste.ee/p/nG8IC - debug build
paste.ee/p/u7gVY - release build

### SpMp version

0.2.4

### Android version

Android 14

### Additional information

SpMp is only loading a portion of my playlists, I'm not sure if this is related. I have close to 70 playlists but only the first 23 alphabetically are showing in the app.

One of the offending playlists: https://music.youtube.com/playlist?list=PL0Cp5aTc0U5ofFeUDTpiYRnbelobZNrCz

**Comment by BlacRyu** [comment] 2023-12-09 17:38
On some other playlists I don't get the error immediately when opening the playlist, but only after reaching the bottom and trying to load more songs. In this case it only shows the error in a frame rather than over the whole app, so I'm able to back out and continue using it.

Log: https://paste.ee/p/cK3uj

Screenshot: 
![Screenshot_20231209-093457](https://github.com/toasterofbread/spmp/assets/10762433/914ccfc0-9ff3-4007-99a0-cedad34b3d17)

**Comment by toasterofbread** [comment] 2023-12-16 13:59
I was unable to reproduce this with the playlist you linked, but this might have been fixed in 8edae6730beed258af7869780fd680cb6df9b069.

**Closed** 2023-12-16 14:38 UTC
Labels: Bug
