### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Vartroc** [toasterofbread/spmp#366] opened 2024-08-27 12:30 UTC
https://paste.ee/p/sGlLq

https://paste.ee/p/F98R7
![Screenshot_2024-08-27-14-25-46-434_com.toasterofbread.spmp.jpg](https://github.com/user-attachments/assets/6c5708f0-be32-4ae1-95e1-554d85edc7a6)

![Screenshot_2024-08-27-14-25-18-077_com.toasterofbread.spmp.jpg](https://github.com/user-attachments/assets/d116a600-00fc-47d2-b584-d9a9c5d58620)

I am new to some and I have just logged in to my Google account and it shows my Google account and all the other options. 

Any help would be appreciated, I think I missed something obvious, but I can't find it.

**Comment by toasterofbread** [comment] 2024-08-27 16:15
Duplicate of #360 (you're not on the latest version).

**Closed by toasterofbread** 2024-08-27 16:15 UTC
