### ISSUE TITLE
Song downloaded not working 

### ISSUE THREAD

**Issue by Sensex00** [toasterofbread/spmp#321] opened 2024-06-14 19:00 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Screenshots / recordings

https://paste.ee/p/BcbSR

### Logs

https://paste.ee/p/BcbSR

### SpMp version

Latest 

### SpMp platform

Android

### OS version

V13

### Additional information

.

**Comment by toasterofbread** [comment] 2024-06-14 19:34
Please provide the required information in the issue template.

Additionally, this appears to be a duplicate of #290, which should have been fixed by c087cf5. What's the latest commit you were able to reproduce this with?

**Comment by Sensex00** [comment] 2024-06-14 19:57
https://github.com/toasterofbread/spmp/assets/168848690/bfc23bb7-1869-42c8-b1e9-d6caf9e58895

**Comment by Sensex00** [comment] 2024-06-14 20:04
I think it is same as https://github.com/toasterofbread/spmp/issues/313#issue-2341601885

**Closed** 2024-07-15 01:09 UTC
Labels: Bug, Waiting for response
