### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by rahulzprofilez** [toasterofbread/spmp#137] opened 2023-09-09 01:50 UTC
kotlin.NotImplementedError: MUSIC_PAGE_TYPE_ARTIST_DISCOGRAPHY
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$Companion.fromBrowseEndpointType(Unknown Source:88)
	at com.toasterofbread.spmp.api.BrowseEndpoint.getMediaItem(Unknown Source:10)
	at com.toasterofbread.spmp.api.BrowseEndpoint.getViewMore(Unknown Source:2)
	at com.toasterofbread.spmp.api.NavigationEndpoint.getViewMore(Unknown Source:4)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invokeSuspend(Unknown Source:1194)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$processDefaultResponse$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.processDefaultResponse(Unknown Source:13)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invokeSuspend(Unknown Source:241)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:8)
	at com.toasterofbread.spmp.api.LoadMediaitemKt$loadMediaItemData$2.invoke(Unknown Source:4)
	at androidx.core.R$dimen.startUndispatchedOrReturn(Unknown Source:4)
	at coil.util.-Contexts.withContext(Unknown Source:71)
	at com.toasterofbread.spmp.api.LoadMediaitemKt.loadMediaItemData(Unknown Source:76)
	at com.toasterofbread.spmp.model.mediaitem.MediaItem$loadGeneralData$2.invokeSuspend(Unknown Source:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:100)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:79)
	Suppressed: coil.network.HttpException: [androidx.compose.ui.platform.MotionDurationScaleImpl@dd54e5a, androidx.compose.runtime.BroadcastFrameClock@54df88b, StandaloneCoroutine{Cancelling}@19e3d7, AndroidUiDispatcher@650a581]

**Comment by toasterofbread** [comment] 2023-09-09 07:19
Duplicate of #114. A release will be published in the next day or two, or you can try a commit build [here](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).

**Closed by toasterofbread** 2023-09-09 07:19 UTC
Labels: Bug
