### ISSUE TITLE
There is no queue , no radio , it only plays one single song

### ISSUE THREAD

**Issue by CodeYannSteff** [toasterofbread/spmp#293] opened 2024-04-20 12:33 UTC
java.lang.NullPointerException
	at dev.toastbits.ytmkt.impl.youtubei.endpoint.YTMSongRadioEndpoint.getSongRadio-BWLJW6A$suspendImpl(SourceFile:46)
	at dev.toastbits.ytmkt.impl.youtubei.endpoint.YTMSongRadioEndpoint$getSongRadio$1.invokeSuspend(SourceFile:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:99)

#**This is the error**
I tried everything from uninstalling and reinstalling, clearing cache, uninstalling for all users , installing an older version , everything .
It plays the first song just fine then does not show any other song in the queue except NULL POINTER EXCEPTION 

# **SOME ADDITIONAL INFO**
ANDROID 14
OPPO COLOR OS 14
OPPO RENO 10 PRO

![Screenshot_2024-04-20-15-37-46-77_e82a23cb50dd4a2f2e01332c4ab3b632.jpg](https://github.com/toasterofbread/spmp/assets/123860819/2108f8bc-5ebb-4769-8130-e89b47bb4e63)

**Comment by toasterofbread** [comment] 2024-04-20 12:38
Duplicate of #292

**Closed by toasterofbread** 2024-04-20 12:38 UTC
