### ISSUE TITLE
song info doesn't show on Bluetooth devices

### ISSUE THREAD

**Issue by gram11111111** [toasterofbread/spmp#393] opened 2024-10-30 00:06 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Updated to the newest version and the song info doesn't show on Bluetooth devices

### Expected behavior

song title, artist name, and album art show up on connected Bluetooth devices 

### Actual behavior

Nothing

### Logs

non

### SpMp version

0.4.2

### SpMp platform

Android

### OS version

Android 12 

### Additional information

Went back to version 0.4.1 and it works fine

**Comment by toasterofbread** [comment] 2024-10-30 00:09
As stated in the release notes, v0.4.2 is identical to v0.4.1 except for a minor change that fixes the way song audio is loaded. If this issue is fixed by reverting to v0.4.1, then it's almost certainly caused by something outside of SpMp (or you're not actually using v0.4.1).

Are you certain you're testing with v0.4.1 and v0.4.2? And which commit did you test the debug version of?

**Comment by gram11111111** [comment] 2024-10-30 00:34
Commit 2eb375c and reverted back to 9654fa8, I completely reinstalled the app when updating to 0.4.2

**Comment by gram11111111** [comment] 2024-10-30 00:51
https://github.com/toasterofbread/spmp/releases/tag/nightly-latest

**Comment by toasterofbread** [comment] 2024-10-30 21:10
I don't have a device to test this with, so if someone could track down the commit that introduces this issue that would be helpful

**Comment by gram11111111** [comment] 2024-11-08 22:57
sorry for the late reply. [6b39afe](https://github.com/toasterofbread/spmp/commit/6b39afe8424327ca0507d210ecb5b48dcbbff9d8) was the first commit that introduces this bug

**Closed** 2024-11-09 21:01 UTC
Labels: Bug
