### ISSUE TITLE
setDataSource error after relaunching spmp on Android 14

### ISSUE THREAD

**Issue by PopCat19** [toasterofbread/spmp#277] opened 2024-03-26 16:07 UTC
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Force close app
2. Clear app cache
3. Launch the app
4. Clear app from recents and relaunch the app until the error `0xFFFFFFEA` appears 

### Expected behavior

App should launch without errors.

### Actual behavior

After launching the app, the error appears until it is relaunched again.

### Screenshots / recordings

![Screenshot_20240326_120408](https://github.com/toasterofbread/spmp/assets/104473808/3e3f4666-41d0-4f31-946b-6860826aa06e)

### Logs

```
---STACK TRACE---
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:284)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:248)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:359)
	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invokeSuspend(SourceFile:31)
	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invoke(SourceFile:2)
	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invoke(SourceFile:1)
	at okio.Okio__OkioKt.startUndispatchedOrReturn(SourceFile:5)
	at kotlin.TuplesKt.withContext(SourceFile:75)
	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1.readLocalSongMetadata(SourceFile:15)
	at com.toasterofbread.spmp.platform.download.MetadataProcessor$DefaultImpls.readLocalSongMetadata$default(Unknown Source:18)
	at com.toasterofbread.spmp.model.mediaitem.library.MediaItemLibraryKt$getAllLocalSongFiles$2$1$1.invokeSuspend(Unknown Source:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@ae24b73, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f92f42e, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@35e253a, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@a923f48, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f795b06, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@33007f4, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@7c02192, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@3ac4de, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@6e0618c, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@32a50ea, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@cf80a78, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@bd491b6, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@edf5624, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@2101342, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@bcdb090, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@290218e, AndroidUiDispatcher@3495a30]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelling}@d0545bc, AndroidUiDispatcher@3495a30]

---LOGCAT (last 135 lines)---
03-26 12:00:58.259 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.MetadataProcessor$DefaultImpls.readLocalSongMetadata$default(Unknown Source:18)
03-26 12:00:58.259 14627 14627 W System.err: 	at com.toasterofbread.spmp.model.mediaitem.library.MediaItemLibraryKt$getAllLocalSongFiles$2$1$1.invokeSuspend(Unknown Source:80)
03-26 12:00:58.259 14627 14627 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-26 12:00:58.259 14627 14627 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
03-26 12:00:58.259 14627 14627 W System.err: 	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
03-26 12:00:58.259 14627 14627 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-26 12:00:58.259 14627 14627 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@ae24b73, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f92f42e, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@35e253a, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@a923f48, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f795b06, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@33007f4, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@7c02192, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@3ac4de, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@6e0618c, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@32a50ea, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@cf80a78, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@bd491b6, AndroidUiDispatcher@3495a30]
03-26 12:00:58.259 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@edf5624, AndroidUiDispatcher@3495a30]
03-26 12:00:58.260 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@2101342, AndroidUiDispatcher@3495a30]
03-26 12:00:58.260 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelling}@bcdb090, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-26 12:00:58.264 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
03-26 12:00:58.264 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:284)
03-26 12:00:58.264 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:248)
03-26 12:00:58.264 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:359)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invokeSuspend(SourceFile:31)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invoke(SourceFile:2)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1$readLocalSongMetadata$2.invoke(SourceFile:1)
03-26 12:00:58.264 14627 14627 W System.err: 	at okio.Okio__OkioKt.startUndispatchedOrReturn(SourceFile:5)
03-26 12:00:58.264 14627 14627 W System.err: 	at kotlin.TuplesKt.withContext(SourceFile:75)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.LocalSongMetadataProcessor_androidKt$LocalSongMetadataProcessor$1.readLocalSongMetadata(SourceFile:15)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.platform.download.MetadataProcessor$DefaultImpls.readLocalSongMetadata$default(Unknown Source:18)
03-26 12:00:58.264 14627 14627 W System.err: 	at com.toasterofbread.spmp.model.mediaitem.library.MediaItemLibraryKt$getAllLocalSongFiles$2$1$1.invokeSuspend(Unknown Source:80)
03-26 12:00:58.264 14627 14627 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
03-26 12:00:58.264 14627 14627 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:107)
03-26 12:00:58.264 14627 14627 W System.err: 	at androidx.fragment.app.Fragment$4.run(SourceFile:105)
03-26 12:00:58.264 14627 14627 W System.err: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-26 12:00:58.264 14627 14627 W System.err: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@ae24b73, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f92f42e, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@35e253a, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@a923f48, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@f795b06, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@33007f4, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@7c02192, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@3ac4de, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@6e0618c, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@32a50ea, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@cf80a78, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@bd491b6, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@edf5624, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@2101342, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelled}@bcdb090, AndroidUiDispatcher@3495a30]
03-26 12:00:58.264 14627 14627 W System.err: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@4717cad, androidx.compose.runtime.BroadcastFrameClock@31cfbe2, StandaloneCoroutine{Cancelling}@290218e, AndroidUiDispatcher@3495a30]
03-26 12:00:58.269 14627 14627 W System.err: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
03-26 12:00:58.269 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
03-26 12:00:58.269 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:284)
03-26 12:00:58.269 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:248)
03-26 12:00:58.269 14627 14627 W System.err: 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:359)
03-26 12:00:58.269 14627 14627
```

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

Android 14 (OneUI 6.0)

### Additional information

I cleared cache because the music playback was not loading.

**Comment by toasterofbread** [comment] 2024-03-26 16:14
Duplicate of #244

**Closed by toasterofbread** 2024-03-26 16:14 UTC
Labels: Bug
